# Generated by Django 3.2.8 on 2021-10-31 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_productvariation_clothing_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_set', to='store_app.cart'),
        ),
    ]
