# Generated by Django 3.2.8 on 2021-11-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='fit',
            field=models.CharField(default='Regular Fit', max_length=256),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size_of_sleeve',
            field=models.CharField(default='Corta', max_length=256),
        ),
    ]
