# Generated by Django 3.2.8 on 2021-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_auto_20211101_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.CharField(default='-1', max_length=256),
        ),
    ]
