# Generated by Django 3.2.8 on 2021-11-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_cart_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='store_app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtag',
            field=models.CharField(choices=[('ARRIBA', 'ARRIBA'), ('ABAJO', 'ABAJO'), ('VESTIDO', 'VESTIDO'), ('ACCESORIO', 'ACCESORIO')], default='ARRIBA', max_length=256),
        ),
    ]
