# Generated by Django 3.2.8 on 2021-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_auto_20211103_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.CharField(default='Default', max_length=256),
        ),
    ]
