# Generated by Django 3.2.8 on 2021-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_auto_20211205_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(default='', max_length=256),
        ),
    ]
