# Generated by Django 3.2.8 on 2021-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_auto_20211205_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='s_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
