# Generated by Django 3.2.8 on 2021-12-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='type',
            field=models.CharField(default='first', max_length=256),
        ),
    ]
