# Generated by Django 3.2.8 on 2021-12-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_productimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Ordered', max_length=256),
        ),
    ]
