# Generated by Django 3.2.8 on 2021-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0022_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund',
            field=models.CharField(default='No refund asked', max_length=256),
        ),
    ]
