# Generated by Django 3.2.8 on 2021-12-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_payment_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collections/'),
        ),
    ]
