# Generated by Django 3.2.8 on 2021-12-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.cart'),
        ),
    ]
